apiVersion: v1
kind: ServiceAccount
metadata:
  name: network-exporter
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-reader
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-nodes
subjects:
- kind: ServiceAccount
  name: network-exporter
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: node-reader
  apiGroup: rbac.authorization.k8s.io
---
kind: Service
apiVersion: v1
metadata:
  name: network-exporter
  namespace: monitoring
spec:
  selector:
    app: network-exporter
  ports:
  - protocol: TCP
    port: 2112
    targetPort: 2112
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: network-exporter
  namespace: monitoring
  labels:
    app: network-exporter
spec:
  selector:
    matchLabels:
      app: network-exporter
  template:
    metadata:
      labels:
        app: network-exporter
    spec:
      serviceAccountName: network-exporter
      containers:
      - name: network-exporter
        image: ghcr.io/amarchese96/mentat:4e3eb93
        ports:
        - containerPort: 2112
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: SLEEP_SECONDS
          value: "5"
